GET http://localhost:3000/projects

###
GET http://localhost:3000/projects/1

###
POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "project-1",
    "description": "test"
}
