version: '3'

services:
  nest-clean-arch-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-clean-arch-app
    container_name: nest-clean-arch-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-clean-arch-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nest-clean-arch-app
    networks:
      - nest-clean-arch-network
networks:
  nest-clean-arch-network:
    driver: bridge
